[2023-08-07 06:46:02,249] {processor.py:153} INFO - Started process (PID=3777) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:46:02,250] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 06:46:02,250] {logging_mixin.py:115} INFO - [2023-08-07 06:46:02,250] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:46:02,253] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:46:02,261] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.014 seconds
[2023-08-07 06:46:33,757] {processor.py:153} INFO - Started process (PID=3823) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:46:33,758] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 06:46:33,759] {logging_mixin.py:115} INFO - [2023-08-07 06:46:33,758] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:46:33,761] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:46:33,769] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.013 seconds
[2023-08-07 06:47:07,440] {processor.py:153} INFO - Started process (PID=3862) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:47:07,441] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 06:47:07,442] {logging_mixin.py:115} INFO - [2023-08-07 06:47:07,442] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:47:07,444] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:47:07,451] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.013 seconds
[2023-08-07 06:47:38,898] {processor.py:153} INFO - Started process (PID=3896) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:47:38,899] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 06:47:38,899] {logging_mixin.py:115} INFO - [2023-08-07 06:47:38,899] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:47:38,902] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:47:38,909] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.012 seconds
[2023-08-07 06:48:09,762] {processor.py:153} INFO - Started process (PID=3937) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:48:09,766] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 06:48:09,767] {logging_mixin.py:115} INFO - [2023-08-07 06:48:09,767] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:48:09,769] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:48:09,776] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.016 seconds
[2023-08-07 06:48:45,127] {processor.py:153} INFO - Started process (PID=3980) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:48:45,132] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 06:48:45,132] {logging_mixin.py:115} INFO - [2023-08-07 06:48:45,132] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:48:45,135] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:48:45,142] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.016 seconds
[2023-08-07 06:49:17,695] {processor.py:153} INFO - Started process (PID=4014) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:49:17,700] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 06:49:17,700] {logging_mixin.py:115} INFO - [2023-08-07 06:49:17,700] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:49:17,703] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:49:17,710] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.016 seconds
[2023-08-07 06:49:49,659] {processor.py:153} INFO - Started process (PID=4050) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:49:49,666] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 06:49:49,667] {logging_mixin.py:115} INFO - [2023-08-07 06:49:49,667] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:49:49,669] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:49:49,678] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.020 seconds
[2023-08-07 06:50:22,867] {processor.py:153} INFO - Started process (PID=4136) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:50:22,874] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 06:50:22,875] {logging_mixin.py:115} INFO - [2023-08-07 06:50:22,875] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:50:22,879] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:50:22,888] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.028 seconds
[2023-08-07 06:50:56,050] {processor.py:153} INFO - Started process (PID=4175) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:50:56,051] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 06:50:56,052] {logging_mixin.py:115} INFO - [2023-08-07 06:50:56,052] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:50:56,056] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:50:56,066] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.019 seconds
[2023-08-07 06:51:29,830] {processor.py:153} INFO - Started process (PID=4213) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:51:29,835] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 06:51:29,836] {logging_mixin.py:115} INFO - [2023-08-07 06:51:29,836] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:51:29,838] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:51:29,845] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.017 seconds
[2023-08-07 06:52:01,055] {processor.py:153} INFO - Started process (PID=4270) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:52:01,062] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 06:52:01,062] {logging_mixin.py:115} INFO - [2023-08-07 06:52:01,062] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:52:01,066] {logging_mixin.py:115} INFO - [2023-08-07 06:52:01,066] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 4, in <module>
    from extrai_infos_clima import tempo
ModuleNotFoundError: No module named 'extrai_infos_clima'
[2023-08-07 06:52:01,066] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:52:01,083] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.031 seconds
[2023-08-07 06:52:36,672] {processor.py:153} INFO - Started process (PID=4315) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:52:36,677] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 06:52:36,678] {logging_mixin.py:115} INFO - [2023-08-07 06:52:36,678] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:52:36,682] {logging_mixin.py:115} INFO - [2023-08-07 06:52:36,681] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 4, in <module>
    from extrai_infos_clima import tempo
ModuleNotFoundError: No module named 'extrai_infos_clima'
[2023-08-07 06:52:36,682] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:52:36,702] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.033 seconds
[2023-08-07 06:53:07,152] {processor.py:153} INFO - Started process (PID=4348) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:53:07,159] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 06:53:07,160] {logging_mixin.py:115} INFO - [2023-08-07 06:53:07,160] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:53:07,163] {logging_mixin.py:115} INFO - [2023-08-07 06:53:07,162] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 4, in <module>
    from extrai_infos_clima import tempo
ModuleNotFoundError: No module named 'extrai_infos_clima'
[2023-08-07 06:53:07,163] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:53:07,180] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.030 seconds
[2023-08-07 06:53:37,962] {processor.py:153} INFO - Started process (PID=4381) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:53:37,967] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 06:53:37,967] {logging_mixin.py:115} INFO - [2023-08-07 06:53:37,967] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:53:37,971] {logging_mixin.py:115} INFO - [2023-08-07 06:53:37,970] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 4, in <module>
    from extrai_infos_clima import tempo
ModuleNotFoundError: No module named 'extrai_infos_clima'
[2023-08-07 06:53:37,971] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:53:37,989] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.029 seconds
[2023-08-07 06:54:08,340] {processor.py:153} INFO - Started process (PID=4417) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:54:08,345] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 06:54:08,345] {logging_mixin.py:115} INFO - [2023-08-07 06:54:08,345] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:54:08,349] {logging_mixin.py:115} INFO - [2023-08-07 06:54:08,349] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 4, in <module>
    from extrai_infos_clima import tempo
ModuleNotFoundError: No module named 'extrai_infos_clima'
[2023-08-07 06:54:08,349] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:54:08,367] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.029 seconds
[2023-08-07 06:54:40,254] {processor.py:153} INFO - Started process (PID=4453) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:54:40,256] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 06:54:40,257] {logging_mixin.py:115} INFO - [2023-08-07 06:54:40,257] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:54:40,263] {logging_mixin.py:115} INFO - [2023-08-07 06:54:40,262] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 4, in <module>
    from extrai_infos_clima import tempo
ModuleNotFoundError: No module named 'extrai_infos_clima'
[2023-08-07 06:54:40,263] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:54:40,285] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.036 seconds
[2023-08-07 06:55:12,342] {processor.py:153} INFO - Started process (PID=4489) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:55:12,343] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 06:55:12,344] {logging_mixin.py:115} INFO - [2023-08-07 06:55:12,344] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:55:12,353] {logging_mixin.py:115} INFO - [2023-08-07 06:55:12,352] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 4, in <module>
    from extrai_infos_clima import tempo
ModuleNotFoundError: No module named 'extrai_infos_clima'
[2023-08-07 06:55:12,354] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:55:12,383] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.046 seconds
[2023-08-07 06:55:48,733] {processor.py:153} INFO - Started process (PID=4526) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:55:48,738] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 06:55:48,738] {logging_mixin.py:115} INFO - [2023-08-07 06:55:48,738] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:55:48,741] {logging_mixin.py:115} INFO - [2023-08-07 06:55:48,741] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 4, in <module>
    from extrai_infos_clima import tempo
ModuleNotFoundError: No module named 'extrai_infos_clima'
[2023-08-07 06:55:48,742] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:55:48,760] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.029 seconds
[2023-08-07 06:56:21,138] {processor.py:153} INFO - Started process (PID=4630) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:56:21,143] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 06:56:21,143] {logging_mixin.py:115} INFO - [2023-08-07 06:56:21,143] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:56:21,146] {logging_mixin.py:115} INFO - [2023-08-07 06:56:21,146] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 4, in <module>
    from extrai_infos_clima import tempo
ModuleNotFoundError: No module named 'extrai_infos_clima'
[2023-08-07 06:56:21,147] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:56:21,162] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.026 seconds
[2023-08-07 06:56:59,028] {processor.py:153} INFO - Started process (PID=4703) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:56:59,029] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 06:56:59,030] {logging_mixin.py:115} INFO - [2023-08-07 06:56:59,030] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:56:59,033] {logging_mixin.py:115} INFO - [2023-08-07 06:56:59,032] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 4, in <module>
    from extrai_infos_clima import tempo
ModuleNotFoundError: No module named 'extrai_infos_clima'
[2023-08-07 06:56:59,033] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:56:59,049] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.023 seconds
[2023-08-07 06:57:29,312] {processor.py:153} INFO - Started process (PID=4736) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:57:29,317] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 06:57:29,317] {logging_mixin.py:115} INFO - [2023-08-07 06:57:29,317] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:57:29,321] {logging_mixin.py:115} INFO - [2023-08-07 06:57:29,320] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 4, in <module>
    from extrai_infos_clima import tempo
ModuleNotFoundError: No module named 'extrai_infos_clima'
[2023-08-07 06:57:29,321] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:57:29,337] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.027 seconds
[2023-08-07 06:58:02,428] {processor.py:153} INFO - Started process (PID=4773) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:58:02,429] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 06:58:02,430] {logging_mixin.py:115} INFO - [2023-08-07 06:58:02,430] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:58:02,434] {logging_mixin.py:115} INFO - [2023-08-07 06:58:02,433] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 4, in <module>
    from extrai_infos_clima import tempo
ModuleNotFoundError: No module named 'extrai_infos_clima'
[2023-08-07 06:58:02,434] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:58:02,450] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.025 seconds
[2023-08-07 06:58:36,464] {processor.py:153} INFO - Started process (PID=4838) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:58:36,465] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 06:58:36,466] {logging_mixin.py:115} INFO - [2023-08-07 06:58:36,465] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:58:36,470] {logging_mixin.py:115} INFO - [2023-08-07 06:58:36,469] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 4, in <module>
    from extrai_infos_clima import CimlaTempo
ModuleNotFoundError: No module named 'extrai_infos_clima'
[2023-08-07 06:58:36,470] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:58:36,487] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.026 seconds
[2023-08-07 06:59:06,825] {processor.py:153} INFO - Started process (PID=4874) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:59:06,830] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 06:59:06,830] {logging_mixin.py:115} INFO - [2023-08-07 06:59:06,830] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:59:06,834] {logging_mixin.py:115} INFO - [2023-08-07 06:59:06,833] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 4, in <module>
    from extrai_infos_clima import CimlaTempo
ModuleNotFoundError: No module named 'extrai_infos_clima'
[2023-08-07 06:59:06,834] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:59:06,850] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.026 seconds
[2023-08-07 06:59:41,810] {processor.py:153} INFO - Started process (PID=4948) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:59:41,814] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 06:59:41,815] {logging_mixin.py:115} INFO - [2023-08-07 06:59:41,815] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:59:42,763] {logging_mixin.py:115} INFO - [2023-08-07 06:59:42,761] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 15, in <module>
    python_callable= tempo.tempo()
  File "/home/daniel/Documents/airflow_dados_tempo//dags/extrai_infos_clima.py", line 25, in tempo
    os.mkdir(file_path)
FileExistsError: [Errno 17] File exists: '/home/daniel/Documents/airflow_dados_tempo/semana=2023-08-07/'
[2023-08-07 06:59:42,763] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 06:59:42,789] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.981 seconds
[2023-08-07 07:00:19,527] {processor.py:153} INFO - Started process (PID=5028) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:00:19,528] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:00:19,528] {logging_mixin.py:115} INFO - [2023-08-07 07:00:19,528] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:00:20,411] {logging_mixin.py:115} INFO - [2023-08-07 07:00:20,410] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 15, in <module>
    python_callable= tempo.tempo()
  File "/home/daniel/Documents/airflow_dados_tempo//dags/extrai_infos_clima.py", line 25, in tempo
    os.mkdir(file_path)
FileExistsError: [Errno 17] File exists: '/home/daniel/Documents/airflow_dados_tempo/semana=2023-08-07/'
[2023-08-07 07:00:20,412] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:00:20,437] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.912 seconds
[2023-08-07 07:00:52,631] {processor.py:153} INFO - Started process (PID=5075) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:00:52,639] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:00:52,639] {logging_mixin.py:115} INFO - [2023-08-07 07:00:52,639] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:00:53,575] {logging_mixin.py:115} INFO - [2023-08-07 07:00:53,574] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 15, in <module>
    python_callable= tempo.tempo()
  File "/home/daniel/Documents/airflow_dados_tempo//dags/extrai_infos_clima.py", line 25, in tempo
    os.mkdir(file_path)
FileExistsError: [Errno 17] File exists: '/home/daniel/Documents/airflow_dados_tempo/semana=2023-08-07/'
[2023-08-07 07:00:53,575] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:00:53,588] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.960 seconds
[2023-08-07 07:01:30,714] {processor.py:153} INFO - Started process (PID=5120) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:01:30,719] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:01:30,719] {logging_mixin.py:115} INFO - [2023-08-07 07:01:30,719] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:01:31,564] {logging_mixin.py:115} INFO - [2023-08-07 07:01:31,564] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 15, in <module>
    python_callable= tempo.tempo()
  File "/home/daniel/Documents/airflow_dados_tempo//dags/extrai_infos_clima.py", line 25, in tempo
    os.mkdir(file_path)
FileExistsError: [Errno 17] File exists: '/home/daniel/Documents/airflow_dados_tempo/semana=2023-08-07/'
[2023-08-07 07:01:31,564] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:01:31,583] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.870 seconds
[2023-08-07 07:02:05,581] {processor.py:153} INFO - Started process (PID=5168) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:02:05,582] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:02:05,582] {logging_mixin.py:115} INFO - [2023-08-07 07:02:05,582] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:02:06,529] {logging_mixin.py:115} INFO - [2023-08-07 07:02:06,529] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 15, in <module>
    python_callable= tempo.tempo()
  File "/home/daniel/Documents/airflow_dados_tempo//dags/extrai_infos_clima.py", line 25, in tempo
    os.mkdir(file_path)
FileExistsError: [Errno 17] File exists: '/home/daniel/Documents/airflow_dados_tempo/semana=2023-08-07/'
[2023-08-07 07:02:06,529] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:02:06,548] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.970 seconds
[2023-08-07 07:02:41,663] {processor.py:153} INFO - Started process (PID=5211) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:02:41,669] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:02:41,670] {logging_mixin.py:115} INFO - [2023-08-07 07:02:41,670] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:02:42,573] {logging_mixin.py:115} INFO - [2023-08-07 07:02:42,572] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 15, in <module>
    python_callable= tempo.tempo()
  File "/home/daniel/Documents/airflow_dados_tempo//dags/extrai_infos_clima.py", line 25, in tempo
    os.mkdir(file_path)
FileExistsError: [Errno 17] File exists: '/home/daniel/Documents/airflow_dados_tempo/semana=2023-08-07/'
[2023-08-07 07:02:42,573] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:02:42,591] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.932 seconds
[2023-08-07 07:03:17,629] {processor.py:153} INFO - Started process (PID=5256) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:03:17,637] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:03:17,637] {logging_mixin.py:115} INFO - [2023-08-07 07:03:17,637] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:03:17,908] {logging_mixin.py:115} INFO - [2023-08-07 07:03:17,908] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 15, in <module>
    python_callable= tempo.tempo()
TypeError: tempo() missing 1 required positional argument: 'self'
[2023-08-07 07:03:17,909] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:03:17,925] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.299 seconds
[2023-08-07 07:03:52,875] {processor.py:153} INFO - Started process (PID=5300) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:03:52,880] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:03:52,880] {logging_mixin.py:115} INFO - [2023-08-07 07:03:52,880] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:03:53,153] {logging_mixin.py:115} INFO - [2023-08-07 07:03:53,152] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 15, in <module>
    python_callable= tempo.tempo()
TypeError: tempo() missing 1 required positional argument: 'self'
[2023-08-07 07:03:53,153] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:03:53,170] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.296 seconds
[2023-08-07 07:04:25,601] {processor.py:153} INFO - Started process (PID=5360) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:04:25,606] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:04:25,606] {logging_mixin.py:115} INFO - [2023-08-07 07:04:25,606] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:04:25,869] {logging_mixin.py:115} INFO - [2023-08-07 07:04:25,868] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo({{data_interval_end.strftime("%Y-%m-%d")}})
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:04:25,869] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:04:25,882] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.283 seconds
[2023-08-07 07:05:02,282] {processor.py:153} INFO - Started process (PID=5418) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:05:02,289] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:05:02,290] {logging_mixin.py:115} INFO - [2023-08-07 07:05:02,290] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:05:02,567] {logging_mixin.py:115} INFO - [2023-08-07 07:05:02,566] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo({{data_interval_end.strftime("%Y-%m-%d")}})
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:05:02,567] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:05:02,585] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.305 seconds
[2023-08-07 07:05:33,740] {processor.py:153} INFO - Started process (PID=5463) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:05:33,740] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:05:33,741] {logging_mixin.py:115} INFO - [2023-08-07 07:05:33,741] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:05:34,037] {logging_mixin.py:115} INFO - [2023-08-07 07:05:34,037] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo({{data_interval_end.strftime("%Y-%m-%d")}})
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:05:34,037] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:05:34,056] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.319 seconds
[2023-08-07 07:06:04,237] {processor.py:153} INFO - Started process (PID=5501) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:06:04,242] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:06:04,243] {logging_mixin.py:115} INFO - [2023-08-07 07:06:04,243] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:06:04,531] {logging_mixin.py:115} INFO - [2023-08-07 07:06:04,530] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo({{data_interval_end.strftime("%Y-%m-%d")}})
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:06:04,531] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:06:04,545] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.310 seconds
[2023-08-07 07:06:35,636] {processor.py:153} INFO - Started process (PID=5545) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:06:35,642] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:06:35,642] {logging_mixin.py:115} INFO - [2023-08-07 07:06:35,642] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:06:35,919] {logging_mixin.py:115} INFO - [2023-08-07 07:06:35,918] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo({{data_interval_end.strftime("%Y-%m-%d")}})
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:06:35,919] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:06:35,932] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.298 seconds
[2023-08-07 07:07:10,744] {processor.py:153} INFO - Started process (PID=5590) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:07:10,751] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:07:10,751] {logging_mixin.py:115} INFO - [2023-08-07 07:07:10,751] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:07:11,046] {logging_mixin.py:115} INFO - [2023-08-07 07:07:11,046] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo({{data_interval_end.strftime("%Y-%m-%d")}})
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:07:11,046] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:07:11,065] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.323 seconds
[2023-08-07 07:07:42,744] {processor.py:153} INFO - Started process (PID=5631) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:07:42,745] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:07:42,745] {logging_mixin.py:115} INFO - [2023-08-07 07:07:42,745] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:07:43,024] {logging_mixin.py:115} INFO - [2023-08-07 07:07:43,024] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo({{data_interval_end.strftime("%Y-%m-%d")}})
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:07:43,024] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:07:43,040] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.304 seconds
[2023-08-07 07:08:16,029] {processor.py:153} INFO - Started process (PID=5675) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:08:16,036] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:08:16,036] {logging_mixin.py:115} INFO - [2023-08-07 07:08:16,036] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:08:16,326] {logging_mixin.py:115} INFO - [2023-08-07 07:08:16,326] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo({{data_interval_end.strftime("%Y-%m-%d")}})
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:08:16,326] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:08:16,344] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.318 seconds
[2023-08-07 07:08:46,863] {processor.py:153} INFO - Started process (PID=5714) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:08:46,864] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:08:46,865] {logging_mixin.py:115} INFO - [2023-08-07 07:08:46,865] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:08:47,174] {logging_mixin.py:115} INFO - [2023-08-07 07:08:47,174] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo({{data_interval_end.strftime("%Y-%m-%d")}})
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:08:47,175] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:08:47,191] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.330 seconds
[2023-08-07 07:09:18,879] {processor.py:153} INFO - Started process (PID=5755) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:09:18,908] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:09:18,909] {logging_mixin.py:115} INFO - [2023-08-07 07:09:18,909] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:09:19,188] {logging_mixin.py:115} INFO - [2023-08-07 07:09:19,187] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo({{data_interval_end.strftime("%Y-%m-%d")}})
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:09:19,188] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:09:19,206] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.331 seconds
[2023-08-07 07:09:56,021] {processor.py:153} INFO - Started process (PID=5804) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:09:56,022] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:09:56,023] {logging_mixin.py:115} INFO - [2023-08-07 07:09:56,022] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:09:56,347] {logging_mixin.py:115} INFO - [2023-08-07 07:09:56,347] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo({{data_interval_end.strftime("%Y-%m-%d")}})
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:09:56,347] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:09:56,361] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.342 seconds
[2023-08-07 07:10:29,797] {processor.py:153} INFO - Started process (PID=5847) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:10:29,798] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:10:29,798] {logging_mixin.py:115} INFO - [2023-08-07 07:10:29,798] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:10:30,096] {logging_mixin.py:115} INFO - [2023-08-07 07:10:30,096] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo({{data_interval_end.strftime("%Y-%m-%d")}})
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:10:30,097] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:10:30,111] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.316 seconds
[2023-08-07 07:11:02,496] {processor.py:153} INFO - Started process (PID=5887) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:11:02,496] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:11:02,497] {logging_mixin.py:115} INFO - [2023-08-07 07:11:02,496] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:11:02,811] {logging_mixin.py:115} INFO - [2023-08-07 07:11:02,810] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo({{data_interval_end.strftime("%Y-%m-%d")}})
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:11:02,811] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:11:02,826] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.332 seconds
[2023-08-07 07:11:34,248] {processor.py:153} INFO - Started process (PID=5931) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:11:34,248] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:11:34,249] {logging_mixin.py:115} INFO - [2023-08-07 07:11:34,249] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:11:34,537] {logging_mixin.py:115} INFO - [2023-08-07 07:11:34,537] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo({{data_interval_end.strftime("%Y-%m-%d")}})
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:11:34,538] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:11:34,557] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.311 seconds
[2023-08-07 07:12:06,496] {processor.py:153} INFO - Started process (PID=5975) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:12:06,496] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:12:06,497] {logging_mixin.py:115} INFO - [2023-08-07 07:12:06,496] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:12:06,805] {logging_mixin.py:115} INFO - [2023-08-07 07:12:06,805] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo({{data_interval_end.strftime("%Y-%m-%d")}})
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:12:06,805] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:12:06,824] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.330 seconds
[2023-08-07 07:12:37,249] {processor.py:153} INFO - Started process (PID=6013) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:12:37,250] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:12:37,251] {logging_mixin.py:115} INFO - [2023-08-07 07:12:37,251] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:12:37,563] {logging_mixin.py:115} INFO - [2023-08-07 07:12:37,562] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo({{data_interval_end.strftime("%Y-%m-%d")}})
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:12:37,563] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:12:37,577] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.330 seconds
[2023-08-07 07:13:12,112] {processor.py:153} INFO - Started process (PID=6058) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:13:12,112] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:13:12,113] {logging_mixin.py:115} INFO - [2023-08-07 07:13:12,113] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:13:12,422] {logging_mixin.py:115} INFO - [2023-08-07 07:13:12,422] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo({{data_interval_end.strftime("%Y-%m-%d")}})
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:13:12,422] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:13:12,435] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.325 seconds
[2023-08-07 07:13:44,289] {processor.py:153} INFO - Started process (PID=6100) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:13:44,290] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:13:44,291] {logging_mixin.py:115} INFO - [2023-08-07 07:13:44,290] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:13:44,609] {logging_mixin.py:115} INFO - [2023-08-07 07:13:44,608] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo({{data_interval_end.strftime("%Y-%m-%d")}})
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:13:44,609] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:13:44,624] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.337 seconds
[2023-08-07 07:14:17,409] {processor.py:153} INFO - Started process (PID=6144) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:14:17,409] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:14:17,410] {logging_mixin.py:115} INFO - [2023-08-07 07:14:17,410] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:14:17,712] {logging_mixin.py:115} INFO - [2023-08-07 07:14:17,711] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo({{data_interval_end.strftime("%Y-%m-%d")}})
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:14:17,712] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:14:17,725] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.318 seconds
[2023-08-07 07:14:53,471] {processor.py:153} INFO - Started process (PID=6188) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:14:53,472] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:14:53,472] {logging_mixin.py:115} INFO - [2023-08-07 07:14:53,472] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:14:53,770] {logging_mixin.py:115} INFO - [2023-08-07 07:14:53,770] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo({{data_interval_end.strftime("%Y-%m-%d")}})
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:14:53,770] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:14:53,784] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.315 seconds
[2023-08-07 07:15:28,260] {processor.py:153} INFO - Started process (PID=6237) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:15:28,261] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:15:28,262] {logging_mixin.py:115} INFO - [2023-08-07 07:15:28,261] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:15:28,542] {logging_mixin.py:115} INFO - [2023-08-07 07:15:28,542] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo({{data_interval_end.strftime("%Y-%m-%d")}})
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:15:28,542] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:15:28,560] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.301 seconds
[2023-08-07 07:16:03,212] {processor.py:153} INFO - Started process (PID=6283) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:16:03,213] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:16:03,214] {logging_mixin.py:115} INFO - [2023-08-07 07:16:03,214] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:16:03,534] {logging_mixin.py:115} INFO - [2023-08-07 07:16:03,533] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo({{data_interval_end.strftime("%Y-%m-%d")}})
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:16:03,534] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:16:03,555] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.346 seconds
[2023-08-07 07:16:37,741] {processor.py:153} INFO - Started process (PID=6340) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:16:37,749] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:16:37,749] {logging_mixin.py:115} INFO - [2023-08-07 07:16:37,749] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:16:38,011] {logging_mixin.py:115} INFO - [2023-08-07 07:16:38,011] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo({{data_interval_end.strftime("%Y-%m-%d")}})
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:16:38,011] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:16:38,028] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.288 seconds
[2023-08-07 07:17:13,901] {processor.py:153} INFO - Started process (PID=6388) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:17:13,902] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:17:13,902] {logging_mixin.py:115} INFO - [2023-08-07 07:17:13,902] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:17:14,186] {logging_mixin.py:115} INFO - [2023-08-07 07:17:14,186] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo(data_interval_end),
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:17:14,186] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:17:14,201] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.301 seconds
[2023-08-07 07:17:45,087] {processor.py:153} INFO - Started process (PID=6430) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:17:45,087] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:17:45,087] {logging_mixin.py:115} INFO - [2023-08-07 07:17:45,087] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:17:45,345] {logging_mixin.py:115} INFO - [2023-08-07 07:17:45,345] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo(data_interval_end),
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:17:45,346] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:17:45,362] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.277 seconds
[2023-08-07 07:18:21,213] {processor.py:153} INFO - Started process (PID=6473) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:18:21,220] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:18:21,221] {logging_mixin.py:115} INFO - [2023-08-07 07:18:21,221] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:18:21,515] {logging_mixin.py:115} INFO - [2023-08-07 07:18:21,514] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo(data_interval_end),
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:18:21,515] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:18:21,532] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.325 seconds
[2023-08-07 07:18:53,510] {processor.py:153} INFO - Started process (PID=6519) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:18:53,511] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:18:53,512] {logging_mixin.py:115} INFO - [2023-08-07 07:18:53,512] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:18:53,790] {logging_mixin.py:115} INFO - [2023-08-07 07:18:53,790] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo(data_interval_end),
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:18:53,790] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:18:53,807] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.304 seconds
[2023-08-07 07:19:25,480] {processor.py:153} INFO - Started process (PID=6561) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:19:25,487] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:19:25,488] {logging_mixin.py:115} INFO - [2023-08-07 07:19:25,488] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:19:25,757] {logging_mixin.py:115} INFO - [2023-08-07 07:19:25,756] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo(data_interval_end),
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:19:25,757] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:19:25,774] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.296 seconds
[2023-08-07 07:19:57,965] {processor.py:153} INFO - Started process (PID=6602) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:19:57,966] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:19:57,966] {logging_mixin.py:115} INFO - [2023-08-07 07:19:57,966] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:19:58,241] {logging_mixin.py:115} INFO - [2023-08-07 07:19:58,241] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo(data_interval_end),
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:19:58,241] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:19:58,261] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.298 seconds
[2023-08-07 07:20:35,028] {processor.py:153} INFO - Started process (PID=6646) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:20:35,036] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:20:35,037] {logging_mixin.py:115} INFO - [2023-08-07 07:20:35,036] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:20:35,329] {logging_mixin.py:115} INFO - [2023-08-07 07:20:35,328] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo(data_interval_end),
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:20:35,329] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:20:35,346] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.321 seconds
[2023-08-07 07:21:12,458] {processor.py:153} INFO - Started process (PID=6690) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:21:12,464] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:21:12,465] {logging_mixin.py:115} INFO - [2023-08-07 07:21:12,465] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:21:12,738] {logging_mixin.py:115} INFO - [2023-08-07 07:21:12,737] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo(data_interval_end),
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:21:12,738] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:21:12,755] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.299 seconds
[2023-08-07 07:21:45,551] {processor.py:153} INFO - Started process (PID=6737) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:21:45,559] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:21:45,560] {logging_mixin.py:115} INFO - [2023-08-07 07:21:45,560] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:21:45,859] {logging_mixin.py:115} INFO - [2023-08-07 07:21:45,858] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo(data_interval_end),
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:21:45,859] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:21:45,876] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.327 seconds
[2023-08-07 07:22:19,303] {processor.py:153} INFO - Started process (PID=6780) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:22:19,309] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:22:19,310] {logging_mixin.py:115} INFO - [2023-08-07 07:22:19,309] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:22:19,585] {logging_mixin.py:115} INFO - [2023-08-07 07:22:19,584] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo(data_interval_end),
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:22:19,585] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:22:19,602] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.303 seconds
[2023-08-07 07:22:50,137] {processor.py:153} INFO - Started process (PID=6820) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:22:50,142] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:22:50,143] {logging_mixin.py:115} INFO - [2023-08-07 07:22:50,143] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:22:50,409] {logging_mixin.py:115} INFO - [2023-08-07 07:22:50,409] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo(data_interval_end),
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:22:50,410] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:22:50,427] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.291 seconds
[2023-08-07 07:23:22,974] {processor.py:153} INFO - Started process (PID=6862) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:23:22,979] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:23:22,980] {logging_mixin.py:115} INFO - [2023-08-07 07:23:22,980] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:23:23,262] {logging_mixin.py:115} INFO - [2023-08-07 07:23:23,261] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo(data_interval_end),
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:23:23,262] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:23:23,279] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.313 seconds
[2023-08-07 07:23:59,237] {processor.py:153} INFO - Started process (PID=6906) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:23:59,243] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:23:59,243] {logging_mixin.py:115} INFO - [2023-08-07 07:23:59,243] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:23:59,547] {logging_mixin.py:115} INFO - [2023-08-07 07:23:59,546] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo(data_interval_end),
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:23:59,547] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:23:59,565] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.331 seconds
[2023-08-07 07:24:33,068] {processor.py:153} INFO - Started process (PID=6951) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:24:33,073] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:24:33,074] {logging_mixin.py:115} INFO - [2023-08-07 07:24:33,073] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:24:33,332] {logging_mixin.py:115} INFO - [2023-08-07 07:24:33,331] {dagbag.py:320} ERROR - Failed to import: /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/daniel/Documents/airflow_dados_tempo/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py", line 20, in <module>
    python_callable= tempo.tempo(data_interval_end),
NameError: name 'data_interval_end' is not defined
[2023-08-07 07:24:33,332] {processor.py:653} WARNING - No viable dags retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:24:33,350] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.284 seconds
[2023-08-07 07:25:03,916] {processor.py:153} INFO - Started process (PID=7063) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:25:03,916] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:25:03,917] {logging_mixin.py:115} INFO - [2023-08-07 07:25:03,917] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:25:04,186] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:25:04,232] {logging_mixin.py:115} INFO - [2023-08-07 07:25:04,232] {manager.py:508} INFO - Created Permission View: can delete on DAG:dados_climaticos
[2023-08-07 07:25:04,242] {logging_mixin.py:115} INFO - [2023-08-07 07:25:04,242] {manager.py:508} INFO - Created Permission View: can edit on DAG:dados_climaticos
[2023-08-07 07:25:04,251] {logging_mixin.py:115} INFO - [2023-08-07 07:25:04,251] {manager.py:508} INFO - Created Permission View: can read on DAG:dados_climaticos
[2023-08-07 07:25:04,251] {logging_mixin.py:115} INFO - [2023-08-07 07:25:04,251] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:25:04,256] {logging_mixin.py:115} INFO - [2023-08-07 07:25:04,256] {dag.py:2398} INFO - Creating ORM DAG for dados_climaticos
[2023-08-07 07:25:04,262] {logging_mixin.py:115} INFO - [2023-08-07 07:25:04,262] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-07-24T00:00:00+00:00, run_after=2023-07-31T00:00:00+00:00
[2023-08-07 07:25:04,283] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.370 seconds
[2023-08-07 07:25:36,222] {processor.py:153} INFO - Started process (PID=7126) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:25:36,223] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:25:36,224] {logging_mixin.py:115} INFO - [2023-08-07 07:25:36,224] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:25:36,555] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:25:36,563] {logging_mixin.py:115} INFO - [2023-08-07 07:25:36,563] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:25:36,577] {logging_mixin.py:115} INFO - [2023-08-07 07:25:36,577] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:25:36,591] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.373 seconds
[2023-08-07 07:26:07,055] {processor.py:153} INFO - Started process (PID=7170) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:26:07,060] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:26:07,061] {logging_mixin.py:115} INFO - [2023-08-07 07:26:07,061] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:26:07,350] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:26:07,358] {logging_mixin.py:115} INFO - [2023-08-07 07:26:07,358] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:26:07,369] {logging_mixin.py:115} INFO - [2023-08-07 07:26:07,369] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:26:07,388] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.335 seconds
[2023-08-07 07:26:42,983] {processor.py:153} INFO - Started process (PID=7215) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:26:42,988] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:26:42,989] {logging_mixin.py:115} INFO - [2023-08-07 07:26:42,989] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:26:43,265] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:26:43,274] {logging_mixin.py:115} INFO - [2023-08-07 07:26:43,273] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:26:43,285] {logging_mixin.py:115} INFO - [2023-08-07 07:26:43,284] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:26:43,300] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.320 seconds
[2023-08-07 07:27:13,957] {processor.py:153} INFO - Started process (PID=7259) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:27:13,958] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:27:13,959] {logging_mixin.py:115} INFO - [2023-08-07 07:27:13,959] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:27:14,259] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:27:14,285] {logging_mixin.py:115} INFO - [2023-08-07 07:27:14,285] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:27:14,290] {logging_mixin.py:115} INFO - [2023-08-07 07:27:14,290] {dag.py:2398} INFO - Creating ORM DAG for dados_climaticos
[2023-08-07 07:27:14,296] {logging_mixin.py:115} INFO - [2023-08-07 07:27:14,296] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-07-24T00:00:00+00:00, run_after=2023-07-31T00:00:00+00:00
[2023-08-07 07:27:14,311] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.356 seconds
[2023-08-07 07:27:44,604] {processor.py:153} INFO - Started process (PID=7341) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:27:44,610] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:27:44,610] {logging_mixin.py:115} INFO - [2023-08-07 07:27:44,610] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:27:44,891] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:27:44,899] {logging_mixin.py:115} INFO - [2023-08-07 07:27:44,899] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:27:44,910] {logging_mixin.py:115} INFO - [2023-08-07 07:27:44,910] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:27:44,924] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.322 seconds
[2023-08-07 07:28:19,138] {processor.py:153} INFO - Started process (PID=7389) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:28:19,145] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:28:19,146] {logging_mixin.py:115} INFO - [2023-08-07 07:28:19,146] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:28:19,470] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:28:19,478] {logging_mixin.py:115} INFO - [2023-08-07 07:28:19,478] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:28:19,489] {logging_mixin.py:115} INFO - [2023-08-07 07:28:19,488] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:28:19,504] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.368 seconds
[2023-08-07 07:28:51,708] {processor.py:153} INFO - Started process (PID=7468) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:28:51,713] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:28:51,713] {logging_mixin.py:115} INFO - [2023-08-07 07:28:51,713] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:28:51,978] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:28:51,986] {logging_mixin.py:115} INFO - [2023-08-07 07:28:51,986] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:28:51,996] {logging_mixin.py:115} INFO - [2023-08-07 07:28:51,996] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:28:52,012] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.306 seconds
[2023-08-07 07:29:22,742] {processor.py:153} INFO - Started process (PID=7536) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:29:22,746] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:29:22,746] {logging_mixin.py:115} INFO - [2023-08-07 07:29:22,746] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:29:23,006] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:29:23,015] {logging_mixin.py:115} INFO - [2023-08-07 07:29:23,015] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:29:23,025] {logging_mixin.py:115} INFO - [2023-08-07 07:29:23,025] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:29:23,041] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.300 seconds
[2023-08-07 07:29:53,881] {processor.py:153} INFO - Started process (PID=7585) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:29:53,888] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:29:53,888] {logging_mixin.py:115} INFO - [2023-08-07 07:29:53,888] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:29:54,144] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:29:54,152] {logging_mixin.py:115} INFO - [2023-08-07 07:29:54,151] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:29:54,162] {logging_mixin.py:115} INFO - [2023-08-07 07:29:54,162] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:29:54,178] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.299 seconds
[2023-08-07 07:30:25,010] {processor.py:153} INFO - Started process (PID=7625) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:30:25,014] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:30:25,015] {logging_mixin.py:115} INFO - [2023-08-07 07:30:25,015] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:30:25,296] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:30:25,306] {logging_mixin.py:115} INFO - [2023-08-07 07:30:25,306] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:30:25,318] {logging_mixin.py:115} INFO - [2023-08-07 07:30:25,318] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:30:25,334] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.327 seconds
[2023-08-07 07:30:58,502] {processor.py:153} INFO - Started process (PID=7672) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:30:58,503] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:30:58,504] {logging_mixin.py:115} INFO - [2023-08-07 07:30:58,504] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:30:58,885] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:30:58,919] {logging_mixin.py:115} INFO - [2023-08-07 07:30:58,919] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:30:58,925] {logging_mixin.py:115} INFO - [2023-08-07 07:30:58,924] {dag.py:2398} INFO - Creating ORM DAG for dados_climaticos
[2023-08-07 07:30:58,934] {logging_mixin.py:115} INFO - [2023-08-07 07:30:58,934] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-07-24T00:00:00+00:00, run_after=2023-07-31T00:00:00+00:00
[2023-08-07 07:30:58,954] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.453 seconds
[2023-08-07 07:31:36,893] {processor.py:153} INFO - Started process (PID=7766) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:31:36,894] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:31:36,895] {logging_mixin.py:115} INFO - [2023-08-07 07:31:36,895] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:31:37,161] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:31:37,169] {logging_mixin.py:115} INFO - [2023-08-07 07:31:37,169] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:31:37,180] {logging_mixin.py:115} INFO - [2023-08-07 07:31:37,179] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:31:37,195] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.304 seconds
[2023-08-07 07:32:08,246] {processor.py:153} INFO - Started process (PID=7810) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:32:08,251] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:32:08,251] {logging_mixin.py:115} INFO - [2023-08-07 07:32:08,251] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:32:08,520] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:32:08,529] {logging_mixin.py:115} INFO - [2023-08-07 07:32:08,529] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:32:08,540] {logging_mixin.py:115} INFO - [2023-08-07 07:32:08,540] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:32:08,556] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.316 seconds
[2023-08-07 07:32:38,774] {processor.py:153} INFO - Started process (PID=7853) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:32:38,779] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:32:38,780] {logging_mixin.py:115} INFO - [2023-08-07 07:32:38,779] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:32:39,060] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:32:39,095] {logging_mixin.py:115} INFO - [2023-08-07 07:32:39,095] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:32:39,100] {logging_mixin.py:115} INFO - [2023-08-07 07:32:39,099] {dag.py:2398} INFO - Creating ORM DAG for dados_climaticos
[2023-08-07 07:32:39,107] {logging_mixin.py:115} INFO - [2023-08-07 07:32:39,107] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-07-24T00:00:00+00:00, run_after=2023-07-31T00:00:00+00:00
[2023-08-07 07:32:39,121] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.349 seconds
[2023-08-07 07:33:18,978] {processor.py:153} INFO - Started process (PID=7943) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:33:18,983] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:33:18,984] {logging_mixin.py:115} INFO - [2023-08-07 07:33:18,984] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:33:19,292] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:33:19,300] {logging_mixin.py:115} INFO - [2023-08-07 07:33:19,300] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:33:19,312] {logging_mixin.py:115} INFO - [2023-08-07 07:33:19,312] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:33:19,328] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.353 seconds
[2023-08-07 07:33:51,929] {processor.py:153} INFO - Started process (PID=7987) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:33:51,930] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:33:51,931] {logging_mixin.py:115} INFO - [2023-08-07 07:33:51,931] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:33:52,215] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:33:52,241] {logging_mixin.py:115} INFO - [2023-08-07 07:33:52,240] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:33:52,245] {logging_mixin.py:115} INFO - [2023-08-07 07:33:52,245] {dag.py:2398} INFO - Creating ORM DAG for dados_climaticos
[2023-08-07 07:33:52,251] {logging_mixin.py:115} INFO - [2023-08-07 07:33:52,251] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-07-24T00:00:00+00:00, run_after=2023-07-31T00:00:00+00:00
[2023-08-07 07:33:52,271] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.344 seconds
[2023-08-07 07:34:24,946] {processor.py:153} INFO - Started process (PID=8067) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:34:24,947] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:34:24,947] {logging_mixin.py:115} INFO - [2023-08-07 07:34:24,947] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:34:25,225] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:34:25,233] {logging_mixin.py:115} INFO - [2023-08-07 07:34:25,233] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:34:25,244] {logging_mixin.py:115} INFO - [2023-08-07 07:34:25,244] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:34:25,256] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.313 seconds
[2023-08-07 07:34:58,457] {processor.py:153} INFO - Started process (PID=8115) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:34:58,459] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:34:58,460] {logging_mixin.py:115} INFO - [2023-08-07 07:34:58,460] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:34:58,755] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:34:58,764] {logging_mixin.py:115} INFO - [2023-08-07 07:34:58,764] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:34:58,776] {logging_mixin.py:115} INFO - [2023-08-07 07:34:58,776] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:34:58,792] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.341 seconds
[2023-08-07 07:35:30,592] {processor.py:153} INFO - Started process (PID=8156) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:35:30,593] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:35:30,594] {logging_mixin.py:115} INFO - [2023-08-07 07:35:30,594] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:35:30,887] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:35:30,894] {logging_mixin.py:115} INFO - [2023-08-07 07:35:30,894] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:35:30,906] {logging_mixin.py:115} INFO - [2023-08-07 07:35:30,906] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:35:30,919] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.329 seconds
[2023-08-07 07:36:02,557] {processor.py:153} INFO - Started process (PID=8200) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:36:02,558] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:36:02,559] {logging_mixin.py:115} INFO - [2023-08-07 07:36:02,559] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:36:02,847] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:36:02,855] {logging_mixin.py:115} INFO - [2023-08-07 07:36:02,855] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:36:02,866] {logging_mixin.py:115} INFO - [2023-08-07 07:36:02,866] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:36:02,881] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.327 seconds
[2023-08-07 07:36:38,506] {processor.py:153} INFO - Started process (PID=8244) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:36:38,511] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:36:38,512] {logging_mixin.py:115} INFO - [2023-08-07 07:36:38,512] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:36:38,803] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:36:38,812] {logging_mixin.py:115} INFO - [2023-08-07 07:36:38,812] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:36:38,824] {logging_mixin.py:115} INFO - [2023-08-07 07:36:38,824] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:36:38,840] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.341 seconds
[2023-08-07 07:37:13,334] {processor.py:153} INFO - Started process (PID=8296) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:37:13,335] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:37:13,336] {logging_mixin.py:115} INFO - [2023-08-07 07:37:13,336] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:37:13,631] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:37:13,660] {logging_mixin.py:115} INFO - [2023-08-07 07:37:13,660] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:37:13,665] {logging_mixin.py:115} INFO - [2023-08-07 07:37:13,664] {dag.py:2398} INFO - Creating ORM DAG for dados_climaticos
[2023-08-07 07:37:13,671] {logging_mixin.py:115} INFO - [2023-08-07 07:37:13,671] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-07-24T00:00:00+00:00, run_after=2023-07-31T00:00:00+00:00
[2023-08-07 07:37:13,689] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.358 seconds
[2023-08-07 07:37:50,779] {processor.py:153} INFO - Started process (PID=8386) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:37:50,784] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:37:50,785] {logging_mixin.py:115} INFO - [2023-08-07 07:37:50,785] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:37:51,070] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:37:51,077] {logging_mixin.py:115} INFO - [2023-08-07 07:37:51,077] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:37:51,089] {logging_mixin.py:115} INFO - [2023-08-07 07:37:51,088] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:37:51,105] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.327 seconds
[2023-08-07 07:38:27,256] {processor.py:153} INFO - Started process (PID=8431) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:38:27,261] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:38:27,262] {logging_mixin.py:115} INFO - [2023-08-07 07:38:27,262] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:38:27,551] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:38:27,559] {logging_mixin.py:115} INFO - [2023-08-07 07:38:27,559] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:38:27,573] {logging_mixin.py:115} INFO - [2023-08-07 07:38:27,573] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:38:27,587] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.337 seconds
[2023-08-07 07:38:57,809] {processor.py:153} INFO - Started process (PID=8469) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:38:57,814] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:38:57,815] {logging_mixin.py:115} INFO - [2023-08-07 07:38:57,815] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:38:58,080] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:38:58,087] {logging_mixin.py:115} INFO - [2023-08-07 07:38:58,087] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:38:58,098] {logging_mixin.py:115} INFO - [2023-08-07 07:38:58,098] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:38:58,113] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.306 seconds
[2023-08-07 07:39:32,335] {processor.py:153} INFO - Started process (PID=8513) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:39:32,342] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:39:32,343] {logging_mixin.py:115} INFO - [2023-08-07 07:39:32,343] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:39:32,610] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:39:32,618] {logging_mixin.py:115} INFO - [2023-08-07 07:39:32,618] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:39:32,630] {logging_mixin.py:115} INFO - [2023-08-07 07:39:32,629] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:39:32,641] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.308 seconds
[2023-08-07 07:40:04,615] {processor.py:153} INFO - Started process (PID=8556) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:40:04,620] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:40:04,621] {logging_mixin.py:115} INFO - [2023-08-07 07:40:04,621] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:40:04,911] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:40:04,920] {logging_mixin.py:115} INFO - [2023-08-07 07:40:04,920] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:40:04,931] {logging_mixin.py:115} INFO - [2023-08-07 07:40:04,931] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:40:04,947] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.337 seconds
[2023-08-07 07:40:37,712] {processor.py:153} INFO - Started process (PID=8596) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:40:37,719] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:40:37,719] {logging_mixin.py:115} INFO - [2023-08-07 07:40:37,719] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:40:37,996] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:40:38,004] {logging_mixin.py:115} INFO - [2023-08-07 07:40:38,004] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:40:38,016] {logging_mixin.py:115} INFO - [2023-08-07 07:40:38,016] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:40:38,031] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.321 seconds
[2023-08-07 07:41:08,487] {processor.py:153} INFO - Started process (PID=8637) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:41:08,488] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:41:08,489] {logging_mixin.py:115} INFO - [2023-08-07 07:41:08,489] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:41:08,767] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:41:08,775] {logging_mixin.py:115} INFO - [2023-08-07 07:41:08,775] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:41:08,785] {logging_mixin.py:115} INFO - [2023-08-07 07:41:08,785] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:41:08,801] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.323 seconds
[2023-08-07 07:41:40,986] {processor.py:153} INFO - Started process (PID=8680) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:41:40,991] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:41:40,992] {logging_mixin.py:115} INFO - [2023-08-07 07:41:40,992] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:41:41,266] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:41:41,273] {logging_mixin.py:115} INFO - [2023-08-07 07:41:41,273] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:41:41,284] {logging_mixin.py:115} INFO - [2023-08-07 07:41:41,284] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:41:41,299] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.315 seconds
[2023-08-07 07:42:11,919] {processor.py:153} INFO - Started process (PID=8717) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:42:11,926] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:42:11,926] {logging_mixin.py:115} INFO - [2023-08-07 07:42:11,926] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:42:12,222] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:42:12,230] {logging_mixin.py:115} INFO - [2023-08-07 07:42:12,230] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:42:12,241] {logging_mixin.py:115} INFO - [2023-08-07 07:42:12,241] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:42:12,257] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.341 seconds
[2023-08-07 07:42:43,081] {processor.py:153} INFO - Started process (PID=8757) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:42:43,082] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:42:43,083] {logging_mixin.py:115} INFO - [2023-08-07 07:42:43,082] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:42:43,375] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:42:43,382] {logging_mixin.py:115} INFO - [2023-08-07 07:42:43,382] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:42:43,394] {logging_mixin.py:115} INFO - [2023-08-07 07:42:43,393] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:42:43,406] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.327 seconds
[2023-08-07 07:43:17,326] {processor.py:153} INFO - Started process (PID=8803) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:43:17,330] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:43:17,330] {logging_mixin.py:115} INFO - [2023-08-07 07:43:17,330] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:43:17,599] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:43:17,625] {logging_mixin.py:115} INFO - [2023-08-07 07:43:17,625] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:43:17,635] {logging_mixin.py:115} INFO - [2023-08-07 07:43:17,635] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:43:17,650] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.327 seconds
[2023-08-07 07:43:48,707] {processor.py:153} INFO - Started process (PID=8842) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:43:48,714] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:43:48,714] {logging_mixin.py:115} INFO - [2023-08-07 07:43:48,714] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:43:48,977] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:43:48,985] {logging_mixin.py:115} INFO - [2023-08-07 07:43:48,985] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:43:48,996] {logging_mixin.py:115} INFO - [2023-08-07 07:43:48,996] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:43:49,008] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.304 seconds
[2023-08-07 07:44:21,006] {processor.py:153} INFO - Started process (PID=8886) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:44:21,007] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:44:21,007] {logging_mixin.py:115} INFO - [2023-08-07 07:44:21,007] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:44:21,277] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:44:21,286] {logging_mixin.py:115} INFO - [2023-08-07 07:44:21,286] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:44:21,297] {logging_mixin.py:115} INFO - [2023-08-07 07:44:21,297] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:44:21,313] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.310 seconds
[2023-08-07 07:44:53,263] {processor.py:153} INFO - Started process (PID=8927) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:44:53,267] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:44:53,268] {logging_mixin.py:115} INFO - [2023-08-07 07:44:53,268] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:44:53,528] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:44:53,537] {logging_mixin.py:115} INFO - [2023-08-07 07:44:53,537] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:44:53,551] {logging_mixin.py:115} INFO - [2023-08-07 07:44:53,551] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:44:53,569] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.308 seconds
[2023-08-07 07:45:25,233] {processor.py:153} INFO - Started process (PID=8967) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:45:25,235] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:45:25,235] {logging_mixin.py:115} INFO - [2023-08-07 07:45:25,235] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:45:25,512] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:45:25,520] {logging_mixin.py:115} INFO - [2023-08-07 07:45:25,520] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:45:25,531] {logging_mixin.py:115} INFO - [2023-08-07 07:45:25,530] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:45:25,546] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.315 seconds
[2023-08-07 07:45:56,031] {processor.py:153} INFO - Started process (PID=9008) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:45:56,032] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:45:56,032] {logging_mixin.py:115} INFO - [2023-08-07 07:45:56,032] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:45:56,297] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:45:56,304] {logging_mixin.py:115} INFO - [2023-08-07 07:45:56,304] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:45:56,315] {logging_mixin.py:115} INFO - [2023-08-07 07:45:56,315] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:45:56,331] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.302 seconds
[2023-08-07 07:46:31,855] {processor.py:153} INFO - Started process (PID=9086) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:46:31,859] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:46:31,860] {logging_mixin.py:115} INFO - [2023-08-07 07:46:31,860] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:46:32,130] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:46:32,138] {logging_mixin.py:115} INFO - [2023-08-07 07:46:32,138] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:46:32,149] {logging_mixin.py:115} INFO - [2023-08-07 07:46:32,149] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:46:32,165] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.312 seconds
[2023-08-07 07:47:03,328] {processor.py:153} INFO - Started process (PID=9152) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:47:03,329] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:47:03,329] {logging_mixin.py:115} INFO - [2023-08-07 07:47:03,329] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:47:03,596] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:47:03,603] {logging_mixin.py:115} INFO - [2023-08-07 07:47:03,603] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:47:03,613] {logging_mixin.py:115} INFO - [2023-08-07 07:47:03,613] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:47:03,628] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.303 seconds
[2023-08-07 07:47:36,190] {processor.py:153} INFO - Started process (PID=9228) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:47:36,195] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:47:36,195] {logging_mixin.py:115} INFO - [2023-08-07 07:47:36,195] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:47:36,468] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:47:36,476] {logging_mixin.py:115} INFO - [2023-08-07 07:47:36,476] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:47:36,487] {logging_mixin.py:115} INFO - [2023-08-07 07:47:36,487] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:47:36,502] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.314 seconds
[2023-08-07 07:48:12,598] {processor.py:153} INFO - Started process (PID=9329) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:48:12,603] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:48:12,603] {logging_mixin.py:115} INFO - [2023-08-07 07:48:12,603] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:48:12,873] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:48:12,881] {logging_mixin.py:115} INFO - [2023-08-07 07:48:12,881] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:48:12,892] {logging_mixin.py:115} INFO - [2023-08-07 07:48:12,892] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:48:12,908] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.312 seconds
[2023-08-07 07:48:45,869] {processor.py:153} INFO - Started process (PID=9426) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:48:45,870] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:48:45,870] {logging_mixin.py:115} INFO - [2023-08-07 07:48:45,870] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:48:46,134] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:48:46,142] {logging_mixin.py:115} INFO - [2023-08-07 07:48:46,142] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:48:46,153] {logging_mixin.py:115} INFO - [2023-08-07 07:48:46,153] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:48:46,169] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.302 seconds
[2023-08-07 07:49:23,050] {processor.py:153} INFO - Started process (PID=9543) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:49:23,055] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:49:23,055] {logging_mixin.py:115} INFO - [2023-08-07 07:49:23,055] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:49:23,342] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:49:23,349] {logging_mixin.py:115} INFO - [2023-08-07 07:49:23,349] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:49:23,360] {logging_mixin.py:115} INFO - [2023-08-07 07:49:23,360] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:49:23,376] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.328 seconds
[2023-08-07 07:49:56,853] {processor.py:153} INFO - Started process (PID=9614) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:49:56,853] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:49:56,854] {logging_mixin.py:115} INFO - [2023-08-07 07:49:56,854] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:49:57,125] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:49:57,133] {logging_mixin.py:115} INFO - [2023-08-07 07:49:57,133] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:49:57,144] {logging_mixin.py:115} INFO - [2023-08-07 07:49:57,144] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:49:57,159] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.309 seconds
[2023-08-07 07:50:31,067] {processor.py:153} INFO - Started process (PID=9660) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:50:31,072] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:50:31,073] {logging_mixin.py:115} INFO - [2023-08-07 07:50:31,072] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:50:31,378] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:50:31,387] {logging_mixin.py:115} INFO - [2023-08-07 07:50:31,386] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:50:31,398] {logging_mixin.py:115} INFO - [2023-08-07 07:50:31,398] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:50:31,415] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.350 seconds
[2023-08-07 07:51:04,551] {processor.py:153} INFO - Started process (PID=9740) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:51:04,558] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:51:04,559] {logging_mixin.py:115} INFO - [2023-08-07 07:51:04,559] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:51:04,842] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:51:04,849] {logging_mixin.py:115} INFO - [2023-08-07 07:51:04,849] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:51:04,860] {logging_mixin.py:115} INFO - [2023-08-07 07:51:04,860] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:51:04,872] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.326 seconds
[2023-08-07 07:51:39,740] {processor.py:153} INFO - Started process (PID=9787) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:51:39,745] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:51:39,745] {logging_mixin.py:115} INFO - [2023-08-07 07:51:39,745] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:51:40,009] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:51:40,017] {logging_mixin.py:115} INFO - [2023-08-07 07:51:40,017] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:51:40,032] {logging_mixin.py:115} INFO - [2023-08-07 07:51:40,032] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:51:40,048] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.310 seconds
[2023-08-07 07:52:10,573] {processor.py:153} INFO - Started process (PID=9879) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:52:10,578] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:52:10,579] {logging_mixin.py:115} INFO - [2023-08-07 07:52:10,579] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:52:10,871] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:52:10,879] {logging_mixin.py:115} INFO - [2023-08-07 07:52:10,878] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:52:10,889] {logging_mixin.py:115} INFO - [2023-08-07 07:52:10,889] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:52:10,902] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.334 seconds
[2023-08-07 07:52:45,409] {processor.py:153} INFO - Started process (PID=9973) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:52:45,410] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:52:45,411] {logging_mixin.py:115} INFO - [2023-08-07 07:52:45,411] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:52:45,693] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:52:45,701] {logging_mixin.py:115} INFO - [2023-08-07 07:52:45,701] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:52:45,712] {logging_mixin.py:115} INFO - [2023-08-07 07:52:45,712] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:52:45,728] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.323 seconds
[2023-08-07 07:53:20,378] {processor.py:153} INFO - Started process (PID=10053) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:53:20,379] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:53:20,380] {logging_mixin.py:115} INFO - [2023-08-07 07:53:20,380] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:53:20,660] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:53:20,669] {logging_mixin.py:115} INFO - [2023-08-07 07:53:20,668] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:53:20,681] {logging_mixin.py:115} INFO - [2023-08-07 07:53:20,680] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:53:20,700] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.323 seconds
[2023-08-07 07:53:52,421] {processor.py:153} INFO - Started process (PID=10138) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:53:52,426] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:53:52,427] {logging_mixin.py:115} INFO - [2023-08-07 07:53:52,426] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:53:52,692] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:53:52,700] {logging_mixin.py:115} INFO - [2023-08-07 07:53:52,700] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:53:52,710] {logging_mixin.py:115} INFO - [2023-08-07 07:53:52,710] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:53:52,726] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.307 seconds
[2023-08-07 07:54:28,942] {processor.py:153} INFO - Started process (PID=10245) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:54:28,943] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:54:28,944] {logging_mixin.py:115} INFO - [2023-08-07 07:54:28,944] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:54:29,215] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:54:29,223] {logging_mixin.py:115} INFO - [2023-08-07 07:54:29,223] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:54:29,234] {logging_mixin.py:115} INFO - [2023-08-07 07:54:29,234] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:54:29,251] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.311 seconds
[2023-08-07 07:55:00,785] {processor.py:153} INFO - Started process (PID=10321) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:55:00,790] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:55:00,791] {logging_mixin.py:115} INFO - [2023-08-07 07:55:00,791] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:55:01,073] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:55:01,081] {logging_mixin.py:115} INFO - [2023-08-07 07:55:01,081] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:55:01,092] {logging_mixin.py:115} INFO - [2023-08-07 07:55:01,092] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:55:01,111] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.332 seconds
[2023-08-07 07:55:34,887] {processor.py:153} INFO - Started process (PID=10421) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:55:34,888] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:55:34,888] {logging_mixin.py:115} INFO - [2023-08-07 07:55:34,888] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:55:35,186] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:55:35,194] {logging_mixin.py:115} INFO - [2023-08-07 07:55:35,194] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:55:35,207] {logging_mixin.py:115} INFO - [2023-08-07 07:55:35,207] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:55:35,225] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.340 seconds
[2023-08-07 07:56:07,366] {processor.py:153} INFO - Started process (PID=10473) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:56:07,367] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:56:07,367] {logging_mixin.py:115} INFO - [2023-08-07 07:56:07,367] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:56:07,640] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:56:07,648] {logging_mixin.py:115} INFO - [2023-08-07 07:56:07,648] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:56:07,659] {logging_mixin.py:115} INFO - [2023-08-07 07:56:07,659] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:56:07,674] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.309 seconds
[2023-08-07 07:56:43,445] {processor.py:153} INFO - Started process (PID=10520) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:56:43,450] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:56:43,450] {logging_mixin.py:115} INFO - [2023-08-07 07:56:43,450] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:56:43,714] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:56:43,721] {logging_mixin.py:115} INFO - [2023-08-07 07:56:43,721] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:56:43,732] {logging_mixin.py:115} INFO - [2023-08-07 07:56:43,732] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:56:43,747] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.304 seconds
[2023-08-07 07:57:14,387] {processor.py:153} INFO - Started process (PID=10562) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:57:14,392] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:57:14,392] {logging_mixin.py:115} INFO - [2023-08-07 07:57:14,392] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:57:14,661] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:57:14,669] {logging_mixin.py:115} INFO - [2023-08-07 07:57:14,669] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:57:14,680] {logging_mixin.py:115} INFO - [2023-08-07 07:57:14,680] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:57:14,696] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.311 seconds
[2023-08-07 07:57:47,426] {processor.py:153} INFO - Started process (PID=10607) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:57:47,431] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:57:47,431] {logging_mixin.py:115} INFO - [2023-08-07 07:57:47,431] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:57:47,744] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:57:47,753] {logging_mixin.py:115} INFO - [2023-08-07 07:57:47,753] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:57:47,765] {logging_mixin.py:115} INFO - [2023-08-07 07:57:47,765] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:57:47,779] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.356 seconds
[2023-08-07 07:58:19,995] {processor.py:153} INFO - Started process (PID=10647) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:58:20,000] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:58:20,000] {logging_mixin.py:115} INFO - [2023-08-07 07:58:20,000] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:58:20,276] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:58:20,284] {logging_mixin.py:115} INFO - [2023-08-07 07:58:20,284] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:58:20,295] {logging_mixin.py:115} INFO - [2023-08-07 07:58:20,295] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:58:20,312] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.319 seconds
[2023-08-07 07:58:52,565] {processor.py:153} INFO - Started process (PID=10692) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:58:52,566] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:58:52,567] {logging_mixin.py:115} INFO - [2023-08-07 07:58:52,567] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:58:52,854] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:58:52,862] {logging_mixin.py:115} INFO - [2023-08-07 07:58:52,862] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:58:52,874] {logging_mixin.py:115} INFO - [2023-08-07 07:58:52,874] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:58:52,887] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.326 seconds
[2023-08-07 07:59:26,628] {processor.py:153} INFO - Started process (PID=10735) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:59:26,635] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 07:59:26,635] {logging_mixin.py:115} INFO - [2023-08-07 07:59:26,635] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:59:26,908] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 07:59:26,916] {logging_mixin.py:115} INFO - [2023-08-07 07:59:26,916] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 07:59:26,927] {logging_mixin.py:115} INFO - [2023-08-07 07:59:26,927] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 07:59:26,940] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.314 seconds
[2023-08-07 08:00:03,206] {processor.py:153} INFO - Started process (PID=10780) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 08:00:03,211] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 08:00:03,212] {logging_mixin.py:115} INFO - [2023-08-07 08:00:03,212] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 08:00:03,504] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 08:00:03,513] {logging_mixin.py:115} INFO - [2023-08-07 08:00:03,513] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 08:00:03,526] {logging_mixin.py:115} INFO - [2023-08-07 08:00:03,526] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 08:00:03,539] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.337 seconds
[2023-08-07 08:00:35,458] {processor.py:153} INFO - Started process (PID=10826) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 08:00:35,465] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 08:00:35,465] {logging_mixin.py:115} INFO - [2023-08-07 08:00:35,465] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 08:00:35,740] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 08:00:35,748] {logging_mixin.py:115} INFO - [2023-08-07 08:00:35,748] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 08:00:35,760] {logging_mixin.py:115} INFO - [2023-08-07 08:00:35,760] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 08:00:35,776] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.321 seconds
[2023-08-07 08:01:07,432] {processor.py:153} INFO - Started process (PID=10866) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 08:01:07,437] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 08:01:07,437] {logging_mixin.py:115} INFO - [2023-08-07 08:01:07,437] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 08:01:07,711] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 08:01:07,719] {logging_mixin.py:115} INFO - [2023-08-07 08:01:07,719] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 08:01:07,730] {logging_mixin.py:115} INFO - [2023-08-07 08:01:07,730] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 08:01:07,747] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.316 seconds
[2023-08-07 08:01:41,133] {processor.py:153} INFO - Started process (PID=10911) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 08:01:41,134] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 08:01:41,134] {logging_mixin.py:115} INFO - [2023-08-07 08:01:41,134] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 08:01:41,397] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 08:01:41,404] {logging_mixin.py:115} INFO - [2023-08-07 08:01:41,404] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 08:01:41,415] {logging_mixin.py:115} INFO - [2023-08-07 08:01:41,415] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 08:01:41,431] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.300 seconds
[2023-08-07 08:02:11,924] {processor.py:153} INFO - Started process (PID=10948) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 08:02:11,931] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 08:02:11,931] {logging_mixin.py:115} INFO - [2023-08-07 08:02:11,931] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 08:02:12,212] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 08:02:12,220] {logging_mixin.py:115} INFO - [2023-08-07 08:02:12,220] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 08:02:12,232] {logging_mixin.py:115} INFO - [2023-08-07 08:02:12,232] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 08:02:12,244] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.323 seconds
[2023-08-07 08:02:48,146] {processor.py:153} INFO - Started process (PID=10996) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 08:02:48,147] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 08:02:48,147] {logging_mixin.py:115} INFO - [2023-08-07 08:02:48,147] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 08:02:48,412] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 08:02:48,419] {logging_mixin.py:115} INFO - [2023-08-07 08:02:48,419] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 08:02:48,431] {logging_mixin.py:115} INFO - [2023-08-07 08:02:48,431] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 08:02:48,447] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.303 seconds
[2023-08-07 08:03:20,540] {processor.py:153} INFO - Started process (PID=11035) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 08:03:20,541] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 08:03:20,541] {logging_mixin.py:115} INFO - [2023-08-07 08:03:20,541] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 08:03:20,814] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 08:03:20,822] {logging_mixin.py:115} INFO - [2023-08-07 08:03:20,822] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 08:03:20,834] {logging_mixin.py:115} INFO - [2023-08-07 08:03:20,833] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 08:03:20,851] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.313 seconds
[2023-08-07 08:03:56,309] {processor.py:153} INFO - Started process (PID=11078) to work on /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 08:03:56,315] {processor.py:641} INFO - Processing file /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py for tasks to queue
[2023-08-07 08:03:56,316] {logging_mixin.py:115} INFO - [2023-08-07 08:03:56,316] {dagbag.py:507} INFO - Filling up the DagBag from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 08:03:56,595] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py
[2023-08-07 08:03:56,603] {logging_mixin.py:115} INFO - [2023-08-07 08:03:56,603] {dag.py:2379} INFO - Sync 1 DAGs
[2023-08-07 08:03:56,614] {logging_mixin.py:115} INFO - [2023-08-07 08:03:56,614] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-08-07T00:00:00+00:00, run_after=2023-08-14T00:00:00+00:00
[2023-08-07 08:03:56,629] {processor.py:161} INFO - Processing /home/daniel/Documents/airflow_dados_tempo/dags/dados_climaticos.py took 0.326 seconds
